syntax = "proto3";
package classification;

// option go_package = "github.com/user/project/proto/classificationpb";
// option go_package = "1.gRPC/proto/classificationpb";
// option go_package = "1.gRPC/proto";
// option go_package = "proto";

// option go_package = "proto/classificationpb"; // if multiple proto files
// option go_package = "proto/";
option go_package = "classification/";

service ClassificationService {
    // rpc Classify (ClassificationRequest) returns (ClassificationResponse);
    rpc Classify (ClassificationRequest) returns (ClassificationResponse) {}
}

message ClassificationRequest {
    string name = 1;
    string appliance = 2;
    string applianceVIB = 3;
}

message ClassificationResponse {
    string response = 1;
}