// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: classification.proto

package protobuf

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ClassificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=userName,proto3" json:"userName,omitempty"`
	ApplianceType string                 `protobuf:"bytes,2,opt,name=applianceType,proto3" json:"applianceType,omitempty"`
	ApplianceVIB  string                 `protobuf:"bytes,3,opt,name=applianceVIB,proto3" json:"applianceVIB,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationRequest) Reset() {
	*x = ClassificationRequest{}
	mi := &file_classification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationRequest) ProtoMessage() {}

func (x *ClassificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationRequest.ProtoReflect.Descriptor instead.
func (*ClassificationRequest) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{0}
}

func (x *ClassificationRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

func (x *ClassificationRequest) GetApplianceType() string {
	if x != nil {
		return x.ApplianceType
	}
	return ""
}

func (x *ClassificationRequest) GetApplianceVIB() string {
	if x != nil {
		return x.ApplianceVIB
	}
	return ""
}

type ClassificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      string                 `protobuf:"bytes,1,opt,name=response,proto3" json:"response,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClassificationResponse) Reset() {
	*x = ClassificationResponse{}
	mi := &file_classification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClassificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClassificationResponse) ProtoMessage() {}

func (x *ClassificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_classification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClassificationResponse.ProtoReflect.Descriptor instead.
func (*ClassificationResponse) Descriptor() ([]byte, []int) {
	return file_classification_proto_rawDescGZIP(), []int{1}
}

func (x *ClassificationResponse) GetResponse() string {
	if x != nil {
		return x.Response
	}
	return ""
}

var File_classification_proto protoreflect.FileDescriptor

const file_classification_proto_rawDesc = "" +
	"\n" +
	"\x14classification.proto\x12\x0eclassification\"}\n" +
	"\x15ClassificationRequest\x12\x1a\n" +
	"\buserName\x18\x01 \x01(\tR\buserName\x12$\n" +
	"\rapplianceType\x18\x02 \x01(\tR\rapplianceType\x12\"\n" +
	"\fapplianceVIB\x18\x03 \x01(\tR\fapplianceVIB\"4\n" +
	"\x16ClassificationResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\tR\bresponse2t\n" +
	"\x15ClassificationService\x12[\n" +
	"\bClassify\x12%.classification.ClassificationRequest\x1a&.classification.ClassificationResponse\"\x00B\x1dZ\x1bgo-router/internal/protobufb\x06proto3"

var (
	file_classification_proto_rawDescOnce sync.Once
	file_classification_proto_rawDescData []byte
)

func file_classification_proto_rawDescGZIP() []byte {
	file_classification_proto_rawDescOnce.Do(func() {
		file_classification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_classification_proto_rawDesc), len(file_classification_proto_rawDesc)))
	})
	return file_classification_proto_rawDescData
}

var file_classification_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_classification_proto_goTypes = []any{
	(*ClassificationRequest)(nil),  // 0: classification.ClassificationRequest
	(*ClassificationResponse)(nil), // 1: classification.ClassificationResponse
}
var file_classification_proto_depIdxs = []int32{
	0, // 0: classification.ClassificationService.Classify:input_type -> classification.ClassificationRequest
	1, // 1: classification.ClassificationService.Classify:output_type -> classification.ClassificationResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_classification_proto_init() }
func file_classification_proto_init() {
	if File_classification_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_classification_proto_rawDesc), len(file_classification_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_classification_proto_goTypes,
		DependencyIndexes: file_classification_proto_depIdxs,
		MessageInfos:      file_classification_proto_msgTypes,
	}.Build()
	File_classification_proto = out.File
	file_classification_proto_goTypes = nil
	file_classification_proto_depIdxs = nil
}
