// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.30.2
// source: classification.proto

package protobuf

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ClassificationService_Classify_FullMethodName = "/classification.ClassificationService/Classify"
)

// ClassificationServiceClient is the client API for ClassificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ClassificationServiceClient interface {
	Classify(ctx context.Context, in *ClassificationRequest, opts ...grpc.CallOption) (*ClassificationResponse, error)
}

type classificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewClassificationServiceClient(cc grpc.ClientConnInterface) ClassificationServiceClient {
	return &classificationServiceClient{cc}
}

func (c *classificationServiceClient) Classify(ctx context.Context, in *ClassificationRequest, opts ...grpc.CallOption) (*ClassificationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClassificationResponse)
	err := c.cc.Invoke(ctx, ClassificationService_Classify_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ClassificationServiceServer is the server API for ClassificationService service.
// All implementations must embed UnimplementedClassificationServiceServer
// for forward compatibility.
type ClassificationServiceServer interface {
	Classify(context.Context, *ClassificationRequest) (*ClassificationResponse, error)
	mustEmbedUnimplementedClassificationServiceServer()
}

// UnimplementedClassificationServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedClassificationServiceServer struct{}

func (UnimplementedClassificationServiceServer) Classify(context.Context, *ClassificationRequest) (*ClassificationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Classify not implemented")
}
func (UnimplementedClassificationServiceServer) mustEmbedUnimplementedClassificationServiceServer() {}
func (UnimplementedClassificationServiceServer) testEmbeddedByValue()                               {}

// UnsafeClassificationServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ClassificationServiceServer will
// result in compilation errors.
type UnsafeClassificationServiceServer interface {
	mustEmbedUnimplementedClassificationServiceServer()
}

func RegisterClassificationServiceServer(s grpc.ServiceRegistrar, srv ClassificationServiceServer) {
	// If the following call pancis, it indicates UnimplementedClassificationServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ClassificationService_ServiceDesc, srv)
}

func _ClassificationService_Classify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClassificationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ClassificationServiceServer).Classify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ClassificationService_Classify_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ClassificationServiceServer).Classify(ctx, req.(*ClassificationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ClassificationService_ServiceDesc is the grpc.ServiceDesc for ClassificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ClassificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "classification.ClassificationService",
	HandlerType: (*ClassificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Classify",
			Handler:    _ClassificationService_Classify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "classification.proto",
}
